# Generated by Django 6.0.1 on 2026-06-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YggdrasilSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(db_index=True, max_length=64)),
                ('server_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yggdrasil_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yggdrasil Session',
                'verbose_name_plural': 'Yggdrasil Sessions',
                'db_table': 'yggdrasil_sessions',
            },
        ),
        migrations.CreateModel(
            name='YggdrasilToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_token', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yggdrasil_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yggdrasil Token',
                'verbose_name_plural': 'Yggdrasil Tokens',
                'db_table': 'yggdrasil_tokens',
            },
        ),
    ]
