# Generated by Django 6.0.1 on 2026-08-10 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('launcher', 'Launcher'), ('admin', 'Admin'), ('ws', 'WebSocket')], db_index=True, default='launcher', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auth Token',
                'verbose_name_plural': 'Auth Tokens',
                'db_table': 'auth_tokens',
            },
        ),
        # AdminToken is deleted in 0004, after 0003 has copied its rows.
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['user', 'scope'], name='auth_tokens_user_id_177945_idx'),
        ),
    ]
