# Generated by Django 5.2.11 on 2026-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cape'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
