# Generated by Django 6.0.1 on 2026-03-21 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_ban_reason_user_banned_until_user_is_banned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('uuid', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minecraft_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'minecraft_sessions',
            },
        ),
    ]
