# Generated by Django 6.0.1 on 2026-02-02 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LauncherToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='launcher_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Launcher Token',
                'verbose_name_plural': 'Launcher Tokens',
                'db_table': 'launcher_tokens',
            },
        ),
    ]
