# Generated by Django 6.0.1 on 2026-06-08 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LauncherToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='launcher_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Launcher Token',
                'verbose_name_plural': 'Launcher Tokens',
                'db_table': 'launcher_tokens',
            },
        ),
        migrations.CreateModel(
            name='LauncherVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Versiya raqami, masalan: 2.2.0', max_length=20)),
                ('platform', models.CharField(choices=[('win32', 'Windows'), ('darwin', 'macOS'), ('linux', 'Linux')], default='win32', max_length=10)),
                ('download_file', models.FileField(help_text='Installer fayli (.exe, .dmg, .tar.gz)', upload_to='launcher/releases/')),
                ('file_size', models.BigIntegerField(default=0, help_text='Fayl hajmi (baytlarda)')),
                ('release_notes', models.TextField(blank=True, default='', help_text="O'zgarishlar ro'yxati")),
                ('is_active', models.BooleanField(default=True, help_text='Aktiv versiya sifatida belgilash')),
                ('force_update', models.BooleanField(default=True, help_text="Majburiy yangilanish (foydalanuvchi o'tkazib yubora olmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Launcher Version',
                'verbose_name_plural': 'Launcher Versions',
                'db_table': 'launcher_versions',
                'ordering': ['-created_at'],
                'unique_together': {('version', 'platform')},
            },
        ),
    ]
