# Generated by Django 5.2.11 on 2026-06-14 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0002_alter_launchertoken_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WSToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WS Token',
                'verbose_name_plural': 'WS Tokens',
                'db_table': 'ws_tokens',
            },
        ),
    ]
