# Generated by Django 5.2.11 on 2026-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0002_launchertoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LauncherVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Versiya raqami, masalan: 2.2.0', max_length=20)),
                ('platform', models.CharField(choices=[('win32', 'Windows'), ('darwin', 'macOS'), ('linux', 'Linux')], default='win32', max_length=10)),
                ('download_file', models.FileField(help_text='Installer fayli (.exe, .dmg, .tar.gz)', upload_to='launcher/releases/')),
                ('file_size', models.BigIntegerField(default=0, help_text='Fayl hajmi (baytlarda)')),
                ('release_notes', models.TextField(blank=True, default='', help_text="O'zgarishlar ro'yxati")),
                ('is_active', models.BooleanField(default=True, help_text='Aktiv versiya sifatida belgilash')),
                ('force_update', models.BooleanField(default=True, help_text="Majburiy yangilanish (foydalanuvchi o'tkazib yubora olmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Launcher Version',
                'verbose_name_plural': 'Launcher Versions',
                'db_table': 'launcher_versions',
                'ordering': ['-created_at'],
                'unique_together': {('version', 'platform')},
            },
        ),
    ]
