# Generated by Django 6.0.1 on 2026-08-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    # Must run after accounts.0003 has copied these rows into auth_tokens.
    dependencies = [
        ('accounts', '0003_migrate_tokens_to_authtoken'),
        ('launcher', '0003_wstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wstoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='LauncherToken',
        ),
        migrations.DeleteModel(
            name='WSToken',
        ),
    ]
