# Generated by Django 6.0.1 on 2026-02-02 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('color_code', models.CharField(default='§7', max_length=10)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ranks',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CCTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('referral_inviter', 'Referral Bonus (Taklif qiluvchi)'), ('referral_invitee', 'Referral Bonus (Taklif qilingan)'), ('daily_bonus', 'Kunlik Bonus'), ('rank_purchase', 'Rank Sotib Olish'), ('admin_add', "Admin tomonidan qo'shildi"), ('admin_remove', 'Admin tomonidan olib tashlandi')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cc_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField(default=0)),
                ('last_claim', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bonus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Bonus',
                'verbose_name_plural': 'Daily Bonuses',
                'db_table': 'daily_bonuses',
            },
        ),
    ]
