from django.urls import path
from .views import (
    PublicServersView,
    PublicStatsView,
    MinecraftVersionsView,
    MinecraftServerListView,
    MinecraftServerDetailView,
    MinecraftServerControlView,
    MinecraftServerCommandView,
    MinecraftServerLogsView,
    MinecraftServerModsView,
    MinecraftServerModDetailView,
    MinecraftServerFilesView,
    ServerJarListView,
    ServerJarDetailView,
    ServerJarVersionsView,
    ServerTypeConfigListView,
    ServerTypeConfigDetailView,
    AdminServersListCreateView,
    AdminServerDetailView,
    PublicSocialLinksView,
    AdminSocialLinksView,
    AdminSocialLinkDetailView,
    MinecraftServerImageUploadView,
    MinecraftServerGalleryUploadView,
)

urlpatterns = [
    path("public/servers/", PublicServersView.as_view(), name="public-servers"),
    path("public/stats/", PublicStatsView.as_view(), name="public-stats"),
    path(
        "public/social-links/",
        PublicSocialLinksView.as_view(),
        name="public-social-links",
    ),
    path(
        "minecraft/server-types/",
        ServerTypeConfigListView.as_view(),
        name="server-type-list",
    ),
    path(
        "minecraft/server-types/<str:server_type>/",
        ServerTypeConfigDetailView.as_view(),
        name="server-type-detail",
    ),
    path("minecraft/jars/", ServerJarListView.as_view(), name="server-jar-list"),
    path(
        "minecraft/jars/<uuid:jar_id>/",
        ServerJarDetailView.as_view(),
        name="server-jar-detail",
    ),
    path(
        "minecraft/jars/versions/",
        ServerJarVersionsView.as_view(),
        name="server-jar-versions",
    ),
    path(
        "minecraft/versions/",
        MinecraftVersionsView.as_view(),
        name="minecraft-versions",
    ),
    path(
        "minecraft/servers/",
        MinecraftServerListView.as_view(),
        name="minecraft-server-list",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/",
        MinecraftServerDetailView.as_view(),
        name="minecraft-server-detail",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/command/",
        MinecraftServerCommandView.as_view(),
        name="minecraft-server-command",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/logs/",
        MinecraftServerLogsView.as_view(),
        name="minecraft-server-logs",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/mods/",
        MinecraftServerModsView.as_view(),
        name="minecraft-server-mods",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/mods/<int:mod_id>/",
        MinecraftServerModDetailView.as_view(),
        name="minecraft-server-mod-detail",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/files/",
        MinecraftServerFilesView.as_view(),
        name="minecraft-server-files",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/images/",
        MinecraftServerImageUploadView.as_view(),
        name="minecraft-server-images",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/gallery/",
        MinecraftServerGalleryUploadView.as_view(),
        name="minecraft-server-gallery",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/gallery/<int:image_id>/",
        MinecraftServerGalleryUploadView.as_view(),
        name="minecraft-server-gallery-delete",
    ),
    path(
        "minecraft/servers/<uuid:server_id>/<str:action>/",
        MinecraftServerControlView.as_view(),
        name="minecraft-server-control",
    ),
    path(
        "admin/servers/",
        AdminServersListCreateView.as_view(),
        name="admin-servers-list",
    ),
    path(
        "admin/servers/<int:pk>/",
        AdminServerDetailView.as_view(),
        name="admin-server-detail",
    ),
    path(
        "admin/social-links/",
        AdminSocialLinksView.as_view(),
        name="admin-social-links",
    ),
    path(
        "admin/social-links/<int:pk>/",
        AdminSocialLinkDetailView.as_view(),
        name="admin-social-link-detail",
    ),
]
